using System.Windows;
using System.Windows.Input;
using TextGame;

namespace Ubiquitus
{
    /// <summary>
    /// Represents the main window of the Ubiquitus application.
    /// Provides the primary user interface for interacting with the game engine.
    /// </summary>
    /// <remarks>
    /// This window serves as the main container for the application's UI elements
    /// and handles user interactions, game display, and command input.
    /// </remarks>
    public partial class MainWindow : Window
    {
        private GameEngine? _gameEngine;

        /// <summary>
        /// Initializes a new instance of the <see cref="MainWindow"/> class.
        /// Sets up the window components and initializes the UI.
        /// </summary>
        public MainWindow()
        {
            InitializeComponent();
            InitializeGame();
            CommandInput.Focus();
        }

        /// <summary>
        /// Initializes the game engine and creates a sample game world
        /// </summary>
        private void InitializeGame()
        {
            _gameEngine = new GameEngine();
            _gameEngine.OutputGenerated += OnGameOutput;

            var (rooms, items, startingRoomId) = CreateSampleWorld();
            _gameEngine.Initialize(rooms, items, startingRoomId);
        }

        /// <summary>
        /// Creates a sample game world for demonstration
        /// </summary>
        /// <returns>Tuple containing rooms dictionary, items dictionary, and starting room ID</returns>
        private (Dictionary<string, Room>, Dictionary<string, Item>, string) CreateSampleWorld()
        {
            var rooms = new Dictionary<string, Room>();
            var items = new Dictionary<string, Item>();

            var entrance = new Room
            {
                Id = "entrance",
                Name = "Entrance Hall",
                Description = "You are standing in a grand entrance hall. Sunlight streams through tall windows.",
                Exits = new Dictionary<string, string>
                {
                    { "north", "library" },
                    { "east", "garden" },
                    { "down", "cellar" }
                },
                Items = new List<string> { "key" }
            };

            var library = new Room
            {
                Id = "library",
                Name = "Library",
                Description = "You are in a dusty library filled with ancient books. The smell of old paper fills the air.",
                Exits = new Dictionary<string, string>
                {
                    { "south", "entrance" }
                },
                Items = new List<string> { "book" }
            };

            var garden = new Room
            {
                Id = "garden",
                Name = "Garden",
                Description = "You are in a beautiful garden. Flowers bloom in every direction, and birds sing overhead.",
                Exits = new Dictionary<string, string>
                {
                    { "west", "entrance" }
                },
                Items = new List<string> { "statue" }
            };

            var cellar = new Room
            {
                Id = "cellar",
                Name = "Cellar",
                Description = "You are in a dark, damp cellar. Strange sounds echo from the shadows.",
                Exits = new Dictionary<string, string>
                {
                    { "up", "entrance" }
                },
                Items = new List<string>()
            };

            rooms.Add(entrance.Id, entrance);
            rooms.Add(library.Id, library);
            rooms.Add(garden.Id, garden);
            rooms.Add(cellar.Id, cellar);

            var key = new Item
            {
                Id = "key",
                Name = "key",
                Description = "A small brass key with intricate engravings.",
                IsCollectable = true,
                IsUsable = true
            };

            var book = new Item
            {
                Id = "book",
                Name = "book",
                Description = "An ancient tome bound in leather. The title reads 'Mysteries of the Unknown'.",
                IsCollectable = true,
                IsUsable = false
            };

            var statue = new Item
            {
                Id = "statue",
                Name = "statue",
                Description = "A marble statue of a robed figure. It's far too heavy to move.",
                IsCollectable = false,
                IsUsable = false
            };

            items.Add(key.Id, key);
            items.Add(book.Id, book);
            items.Add(statue.Id, statue);

            return (rooms, items, "entrance");
        }

        /// <summary>
        /// Handles output generated by the game engine
        /// </summary>
        private void OnGameOutput(object? sender, string message)
        {
            Dispatcher.Invoke(() =>
            {
                OutputTextBlock.Text += message + "\n";
                OutputScrollViewer.ScrollToEnd();
            });
        }

        /// <summary>
        /// Handles the Send button click event
        /// </summary>
        private void SendButton_Click(object sender, RoutedEventArgs e)
        {
            ProcessCommand();
        }

        /// <summary>
        /// Handles the Enter key press in the command input
        /// </summary>
        private void CommandInput_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.Key == Key.Enter)
            {
                ProcessCommand();
            }
        }

        /// <summary>
        /// Processes the command entered by the user
        /// </summary>
        private void ProcessCommand()
        {
            var command = CommandInput.Text.Trim();
            if (string.IsNullOrWhiteSpace(command))
                return;

            OutputTextBlock.Text += $"\n> {command}\n";
            OutputScrollViewer.ScrollToEnd();

            _gameEngine?.ProcessCommand(command);

            CommandInput.Clear();
            CommandInput.Focus();
        }
    }
}